spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=UTF-8
    username: root
    password: sunb
    name: activiti
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    ROOT: warn
    com.sunb: debug
    org.springframework.security: debug
    org.springframework.boot.actuate: debug
management:
  security:
    enabled: false
#security:
#  user:
#    name: sunbo
#    password: sunbo




