spring:
  activiti:
    database-schema: activiti
    database-schema-update: true
    history-level: full
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=UTF-8
    username: root
    password: sunbo
    name: activiti
    driver-class-name: com.mysql.jdbc.Driver
logging:
  pattern:
    level: debug



